### PR TITLE
WIP#148 - Implementing range in HTTP

### PR DESCRIPTION
**Pull request by SzymonPajzert**
#148

### CODE REVIEW

**Comment by mgautierfr** [comment]
Thank you for this PR.
Can you explain a bit more why you have made this changes ?
I know it is to fix #148 but can you be more explicit ? (Why the previous code was not working, what do you change, why you choose to make this changes, ...)

It seems that in you commit, there is some changes that are more cosmetics (move some code in specific method, make some members public (why ?)). And there is some code to fix the issue (but it is difficult to find in the middle of all the other changes). It may be better to make several commits in this situation.

The WIP is real or you forget to remove it ?

**Comment by SzymonPajzert** [comment]
Hi, WIP is real, because I want to add tests first to test the server. I thought of using googletest library, but if you have any better idea, please let me know.

I will add new changes and document all next week, I opened this PR because this code was lying at my computer and I nearly forgot about it.

**Comment by mgautierfr** [comment]
> I thought of using googletest library, but if you have any better idea, please let me know.
No better idea googletest is good. It is what we use in other projects.

**Comment by kelson42** [comment]
@SzymonPajzert Any feedback about that PR? We would really like to carry on fixing that bug.

**Comment by kelson42** [comment]
@SzymonPajzert It looks like this PR is somehow stuck! Any chance that on your side you fix the last problems?

**Comment by SzymonPajzert** [comment]
Sorry for taking so long to finish this PR, I lost track of it at some
point. I can revive it at the beginning of May, would it be ok with you?

**Comment by kelson42** [comment]
@SzymonPajzert Definitely :) I would be really happy if you could finish the PR. Like @mgautierfr said, try to keep your PR specific and not huge. If you can put part of your improvments in separate PRs, please do it. That will simplify a lot the work of review.
@mgautierfr Anything to add?

**Comment by SzymonPajzert** [comment]
I started implementing tests for the feature. I want to extract the functionality and test with regression test if my code works.

The only way I can see this implemented is via Dependency Injection on `accessHandlerCallback`. We would add custom handler as parameter to abstract choice of response after `/* Prepare the variables */`. This way we can plug our own code to generate responses and not worry about connecting to database, reading files, etc. I've implemented that already and it seems fine.

However, I also need to abstract somehow everything that depends on `connection` in that function, to not create instance of that object only for testing. This would add second dependency and I wonder if that won't be too much for testing this only feature.

If you don't plan on using googletest in this project, I would feel better just cleaning the code of unnecessary changes and allow you to test it yourself, without implementing automatic tests. If you want to use googletest, please tell me what you think about my approach.

**Comment by kelson42** [comment]
@mgautierfr Could you please give a feedback to @SzymonPajzert last comment?

**Comment by kelson42** [comment]
@mgautierfr Now that @rgaudin has fixed many problems in the ZIM files related to the video playing... we strongly suspect that this bug impacts randomly the users. All of this start to be really urgent.

**Pull request closed without merging**
