### PR TITLE
to add footer in server page

### PR DESCRIPTION
**Pull request by Bhavnaharitsa**
The recent issue on adding footer " powered by Kiwix " in server

### CODE REVIEW

**Comment by kelson42** [comment]
@Bhavnaharitsa You messed up your PR, only your commit should appear. Secure that your branch is base on git master HEAD.

**Comment by Bhavnaharitsa** [comment]
Okay!!! Where can I get the file for html server page?

**Comment by mgautierfr** [comment]
Please rebase this PR. Now you want to merge far more commit than necessary.

**Comment by kelson42** [comment]
Closing the PR because not active anymore... I can not find anything about the implementation of the related ticket eather.

**Pull request closed without merging**
