### PR TITLE
adding custom url location

### PR DESCRIPTION
**Pull request by swiftugandan**
This is a solution for #31.

Adds a param --urlRootLocation=/URL_ROOT which allows kiwix to be loaded from http://my.domain/URL_ROOT/

### CODE REVIEW

**Comment by swiftugandan** [comment]
I have done some manual testing on this (discovered bugs, and fixed them). seems to be stable now.

**Comment by mgautierfr** [comment]
Thanks @swiftugandan for this patch !

This us great and it seems to globally work. However I have two small remarks :

- Your second commit ("fixing argument flag") should be squash with you first one as it is clearly a fix of the code you've written in you first commit. (Your third commit is ok as it can be considered as an extra step in your branch, and I like separated small commits :) )
- I've tested with a absolute urlRootLocation without a starting `/` (`FOO` instead of `/FOO`). I know that in the small usage text, you have specified with a `/`. But it is better to handle this case and be sure that urlRootLocation is always properly formatted instead of assuming that user will enter the correct thing.

Can you change this ?

**Comment by swiftugandan** [comment]
@mgautierfr 

* I have handled the case of the rootLocation with prefix /
* my git skills are not that great to do the squashing :(

Hope this is sufficient ...

**Comment by swiftugandan** [comment]
@mgautierfr

    I have handled the case of the rootLocation with prefix /
    my git skills are not that great to do the squashing :(

Hope this is sufficient ...

**Comment by swiftugandan** [comment]
closing this pull request, as @mgautierfr has made changes which conflict, that I need to fix ..

**Comment by mgautierfr** [comment]
Indeed it is pretty complex to rebase a `master` branch... I advice you to :
- Create a specific "feature branch" for your change : 
`git checkout -b my_branch_name`
- Make your change and commit as usual.
- Push your feature branch to your github repository
`git push -u origin my_branch_name`
- create a pull request using your branch `my_branch_name` instead of master.

This way, you can rebase your branch on top of the last changes with `git rebase` or even change your branch with `git rebase -i`.
Then you can update your PR simply by force pushing your branch : `git push -f`

**Pull request closed without merging**
