### PR TITLE
Improved taskbar #160 #59

### LINKED ISSUE #160: Improvement of the kiwix-serve toolbar labelling
The navigation system within the display is unclear to the user. At the top of the screen, there is a navigation bar that displays

Library -- Home -- Random.

Library actually brings us back to the home page of the entire bundle. Home brings us back to the home of the offline resource (eg, Wikipedia offline). It would be way clearer to rename those buttons, with labels becoming

Home -- Wikipedia -- Random
or
Home -- WIktionary -- Random
or
Home -- Wikiquote -- Random

### PR DESCRIPTION
**Pull request by kelson42**
Fix #160

### CODE REVIEW

**Comment by mgautierfr** [comment]
Can you describe where do `&#x1f3e0;`, `&#x1f4a1;`, `&#x1F3B2;`and `&#x1f3e0;` come from ?

On Firefox it renders this way :
capture du 2018-06-12 17-16-36
 and on chrome :
capture du 2018-06-12 17-17-57

None of them seems totally correct for me :
 - the `home` is difficult to understand on firefox.
 - the `search` is awful on chrome. (And should it be a magnifying glass instead of light bulb ?)
 - the dice make me think of play, not random.

Maybe include real icons would avoid to different uncontrolled displaying depending of the browser and the font used ? Or maybe use fontawsome ?

When the default value of the title is displayed ? (And what it look like ?) 
The global search bar is not changed.
Should we keep the plain text somewhere (as a tooltip maybe) to help screen reader ?
It doesn't fix #59, kiwix-serve is still not localized (the search result page at least)

**Comment by kelson42** [comment]
I have made a new commit with:
* magnifying glass (instead of light bulb)
* put default title to empty string.

**Comment by kelson42** [comment]
@mgautierfr For some reason, the CI does not pass anymore, even after this last trivial commit!

**Comment by sushmitapundir1993** [comment]
Hi,

can you help me to install dockerized-kiwix-server in linux?

I am stucked. when I run "docker build -t kiwix-serve" command, dockerized-
kiwix-server -> scripts -> ./makelibrary.sh script gave error: kiwix-manage
Command not found.
Please help me out.

Thanks,
Sushmita

**Comment by kelson42** [comment]
@sushmitapundir1993 This is a Pull Request, if you have a question or a bug report regarding kiwix-serve, please open a ticket https://github.com/kiwix/kiwix-tools/issues/new

**Comment by mgautierfr** [comment]
FWI : The new icon on firefox is :
capture du 2018-06-15 18-26-05

and on chrome :
capture du 2018-06-15 18-25-50

I've added a commit to also change the global taskbar.

**Pull request merged**
