### PR TITLE
kiwix-serve can monitor and reload the library automatically

### LINKED ISSUE #476: kiwix-serve should reload automatically content (library/files) if files change
This is a follow up of #243 and request to implement a library/ZIM file monitoring to relaunch a soft loading if necessary

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Fixes #476

If started with the `--monitorLibrary` option (or its short variant `-M`) `kiwix-serve` monitors the input library files and reloads the library automatically.

Only the timestamp of the library file(s) is monitored (if there are multiple library files the most recently modified file's timestamp is used). The library is reloaded when the monitored timestamp grows.

SIGHUP makes `kiwix-serve` to reload the library unconditionally (even if the file hasn't changed).

### CODE REVIEW

**Comment by kelson42** [comment]
@veloman-yunkan Thx for the PR. What does your last comment means regarding Windows? iMO It shoukd works the same whatever the platform,

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Thx for the PR. What does your last comment means regarding Windows? iMO It shoukd works the same whatever the platform.
> 
> It should be optional as well, something like —monitorLibrary.

@kelson42 I included the fix in the Windows build too (but didn't test it). I also added the `--monitorLibrary` option.

Note that the support for reloading the library on SIGHUP was dropped. Should I restore it?

**Comment by kelson42** [comment]
> Note that the support for reloading the library on SIGHUP was dropped. Should I restore it?

Thx for your quick move based on my comment. Sounds good.

Hmmm, yes definitly... I don't really understand why this has been dropped, we just introduced it!

From a general point of view (kind of mine):
* The SIGHUP is the POSIX solution for systems run by IT people, where kiwix-serve is part of a more complex infrastructure.
* This ticket/PR is a kind of alternative feature but for people which don't want or can explicitly deal with signals.

**Comment by veloman-yunkan** [comment]
> > Note that the support for reloading the library on SIGHUP was dropped. Should I restore it?
> 
> Hmmm, yes definitly... I don't really understand why this has been dropped, we just introduced it!
> 

@kelson42 I thought that forced library reloading on SIGHUP was a temporary solution until automatic reloading is implemented. I will restore it shortly.

**Comment by kelson42** [comment]
> > > Note that the support for reloading the library on SIGHUP was dropped. Should I restore it?
> > 
> > 
> > Hmmm, yes definitly... I don't really understand why this has been dropped, we just introduced it!
> 
> @kelson42 I thought that forced library reloading on SIGHUP was a temporary solution until automatic reloading is implemented. I will restore it shortly.

OK. No, it is an alternative.

**Comment by veloman-yunkan** [comment]
@kelson42 Handling of SIGHUP is restored. The PR seems to be final (pending only review by @mgautierfr).

**Review by mgautierfr — APPROVED** [review]
LGTM

**Pull request merged**
