### PR TITLE
adding custom url location

### PR DESCRIPTION
**Pull request by swiftugandan**
This is a solution for #31.

Adds a param --urlRootLocation=/URL_ROOT which allows kiwix to be loaded from http://my.domain/URL_ROOT/

### CODE REVIEW

**Comment by swiftugandan** [comment]
Travis is failing to run the job with with **"error: could not create '/usr/local/lib/python3.4/dist-packages/mesonbuild': Permission denied"**

Please help fix it ...

**Comment by mgautierfr** [comment]
This has been fixed on last master.

Please rebase (not merge) the PR on new master and travis should be OK.

**Comment by swiftugandan** [comment]
Clicked 'update branch' button, expecting a rebase but got a merge. Is that OK?

**Comment by kelson42** [comment]
@swiftugandan Please rebase, doing a merge here is kind of messy.

**Comment by swiftugandan** [comment]
doing another one

**Pull request closed without merging**
