### PR TITLE
Refresh deb packages CI/CD

### PR DESCRIPTION
**Pull request by kelson42**
Add new distribution Ubuntu noble. Unfortunately we requires nos latest version of libzim9 and libkiwix14 which are not on Debian, so I had to comment out all Debian related recipes. See https://github.com/kiwix/libkiwix/issues/1115

### CODE REVIEW

**Comment by kelson42** [comment]
@tusharpm Do you have an idea this time why it fails... because I don't have one anymore :(

**Comment by tusharpm** [comment]
[libkiwix-dev has a different version](https://github.com/kiwix/libkiwix/commit/e096c7e2fd8f04c72b3393deb773977c2141cc7b#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0R25) which fails to install as build dependencies for kiwix-tools. A fix there *might* fix this build.
However, I don't know the utility of maintaining a kiwixteam PPA while the Ubuntu PPA [includes](https://launchpad.net/ubuntu/+source/zim-tools) [the](https://launchpad.net/ubuntu/+source/libzim) [same](https://launchpad.net/ubuntu/+source/kiwix-tools) [packages](https://launchpad.net/ubuntu/+source/libkiwix).

**Comment by kelson42** [comment]
> [libkiwix-dev has a different version](https://github.com/kiwix/libkiwix/commit/e096c7e2fd8f04c72b3393deb773977c2141cc7b#diff-2a13f1344504379e877324d3a0375adcbcb4cb27d7e575ad8f4618a52d6a00e0R25) which fails to install as build dependencies for kiwix-tools. A fix there _might_ fix this build. 

Indeed, I can not understand how I miss this! Thank you!

> However, I don't know the utility of maintaining a kiwixteam PPA while the Ubuntu PPA [includes](https://launchpad.net/ubuntu/+source/zim-tools) [the](https://launchpad.net/ubuntu/+source/libzim) [same](https://launchpad.net/ubuntu/+source/kiwix-tools) [packages](https://launchpad.net/ubuntu/+source/libkiwix).

AFAIK this is only a copy of the debian repo.

**Comment by kelson42** [comment]
@tusharpm Unfortunately it still fails, will retry in a few hours to be sure the new libkiwix package has been properly taken in account.

**Pull request merged**
