### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by mgautierfr**
This are mainly fixes related to changes made in other repositories.

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr What is the plan with that PR?

**Comment by kelson42** [comment]
@mgautierfr I think we should close that PR and delete the branch. All of this looks pretty much outdated to me?!

**Comment by veloman-yunkan** [comment]
@mgautierfr Once again drawing attention to this PR.

**Comment by kelson42** [comment]
@veloman-yunkan Do you really think this PR is valuable? If still valuable it should be done in kiwix-lib probably?

**Comment by veloman-yunkan** [comment]
@kelson42 The only reason I commented on this PR is because I think that such small changes shouldn't stick around for so long. The penging task list must be reviewed and cleaned up from time to time.

**Comment by kelson42** [comment]
@veloman-yunkan I 200% agree but I can not fix the problem myself. Would you be able to review it and merge it?

**Comment by veloman-yunkan** [comment]
@kelson42 Yes, I will do that

**Comment by veloman-yunkan** [comment]
`static/server/meson.build` was [deleted](https://github.com/kiwix/kiwix-tools/pull/315/files#diff-3808833f3400ef88477c28fedc86077e) while moving the server code from `kiwix-tools` (PR #315) to `kiwix-lib` (kiwix/kiwix-lib#246). The corresponding file [`static/meson.build`](https://github.com/kiwix/kiwix-lib/blob/64dfea2547334e915d31ba08b66e32c21e3111db/static/meson.build) in `kiwix-lib` has these changes.

**Pull request closed without merging**
