### PR TITLE
This fixes the redundant error message when the kiwix server fails to start

### LINKED ISSUE #483: kiwix-serve displays same output twice if a port in use is given as argument
If I give a port which is already in use, kiwix-serve displays the following output twice
`Unable to instantiate the HTTP daemon. The port 8080 is maybe already occupied or need more permissions to be open. Please try as root or with a port number higher or equal to 1024.`

Image -  (left command was used first)
image

### PR DESCRIPTION
**Pull request by karandeeppotato**
Fixes #483

### CODE REVIEW

**Review by veloman-yunkan — CHANGES_REQUESTED** [review]
The fix looks good to me. However, the commit message must be improved.

1. Fit the commit summary within the 72 character limit
2. Describe in the commit body why the removed error message is redundant

**Comment by mgautierfr** [comment]
I totally agree with @veloman-yunkan 
I would simply add that the summary must describe what the commit does ("remove duplicate ...").
The why is useful but must be written in the commit message.

**Comment by karandeeppotato** [comment]
@veloman-yunkan 
Hello, I have followed the commit guidelines as told by you 
Please check

**Comment by maneeshpm** [comment]
@karandeeppotato I think we can improve it further. The commit summary (first line of commit) should be concise (like `Remove redundant error message from server start`) and the commit body (next line and below) should provide the description and need for the commit.

Considering that commit messages are permanent addition to our project, please be attentive for any typos and capitalizations so our work looks good to other contributors :wink:

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Hello, I have followed the commit guidelines as told by you Please check

Unfortunately, I can't agree. The commit message still consists of a single line that is too long. Please rewrite it as follows:

> Removed a redundant error message from kiwix-serve
>
> The error message about failing to open the specified port was produced both
> by `kiwix-tools/src/server/kiwix-serve.cpp` and by the `InternalServer`
> constructor (in `libkiwix/src/server/internalServer.cpp`).

**Comment by veloman-yunkan** [comment]
And please also fix the title of this PR

**Comment by karandeeppotato** [comment]
Really sorry for all the trouble @veloman-yunkan 🤐
Actually I am new to GitHub and this is my first contribution so I was confused about the commit message.
Now that I have read the GitHub commit message documentation and your comment, I will finally do it correctly :D

**Review by veloman-yunkan — APPROVED** [review]

**Pull request merged**
