### PR TITLE
Make server toolbar auto-hide and collapse buttons into dropdown on small screens

### LINKED ISSUE #294: Improve kiwix-serve toolbar layout
Currently the toolbar layout on Kiwix-serve is not convenient for users on very small screens (see also #285). There are currently five fields on the top bar: Home (brings the user back to the full zim library)/ File name (which is another form of "Home", but to the zim files' start page) / random / search field / search button
The below improvement has been suggested:

This proposal in #285 is pretty neat, with two caveats:
- Can we do without the text? If it is to be used in non-english languages, it would be more efficient to proceed with icons only (and save space);
- in the case of KaiOS users being online and accessing directly a specific zim file, we might not want to allow them to access the full library. Is it possible to hide the Home/Library button when accessing a specific zim file (e.g. we produce kaiOS-tagged zims, and kiwix-tools would be able to parse this and know that the Library button need not appear?

### PR DESCRIPTION
**Pull request by ISNIT0**
Kapture 2019-06-17 at 14 12 20-min
Kapture 2019-06-17 at 13 44 58-min

Closes #294

### CODE REVIEW

**Comment by kelson42** [comment]
On firefox fullscreen, I see a checkbox now and the I can not reproduce the kind of behavious you have yon the video.

**Comment by ISNIT0** [comment]
@kelson42 Which version of FireFox?
It works for me...

For the hiding/showing of the bar, the page must be <520px wide when it loads

**Comment by kelson42** [comment]
OK, my bad, caching problem. On my side:
* Looks good
* Search button should be removed (like in the mockup)
* In many places things are not really aligned properly

**Comment by ISNIT0** [comment]
@kelson42 I've made some more changes - could you take a look please?

**Comment by kelson42** [comment]
Still many problems (tested with recent Firefox):
* if visible arrow should be vertically aligned with the buttons, search box
* Search cursor is over search icon
* if arrow visible, searchbar top padding/margin increases, it should stay the same so that is is properly vertically aligned in the middle of the bar
* overall top/lef/rigth/bottom margin/padding around buttons seems to have increased, we should probably reduce it a bit
* Arrow should never be below the searchbar, search bar should never grow in height
* I don't like the arrow icon, is it not big enough and the style of the one in your mockup was better

**Comment by kelson42** [comment]
New Feedback:
* Arrow looks better but this is really too small, it is barely visible. I would like to have it two times bigger.
* On large resolution, it still does not behave properly:
  * bar hight increases by clicking on the search box - it should not
  * other buttons disappear, they should not
  * IMO, it would be better to just keep the magnify-glass visible by clicking... so just start the cursor a few pixels on the right of the icon
* So mgmt of the searchbox width is really wrong. It's increasing and decreasing without any logic (at least to me). If the arrow is visible, the searchbar should be fullwidth and just beside the arrow.

**Comment by ISNIT0** [comment]
- [ ] Increase arrow size
- [ ] Fix larger resolution search box issues

The search box size changes are the same as before. The only difference being that now on small screens it takes up the full width of the top bar when focused.

Button padding and margins haven't been changed

**Comment by ISNIT0** [comment]
@kelson42 Made a few changes, could you take a look again please?

**Comment by ISNIT0** [comment]
@kelson42 The "jumping" of the searchbar width on scaling is actually very good for usability. 
Without the specific points it's near-impossible for the searchbar to be sensibly sized all the time.

Also, the fact that it jumps is not such a bad thing because users will rarely be resizing (especially at small sizes)

**Comment by kelson42** [comment]
@ISNIT0 Can you please give me a feedback of all the points I have reported before asking to review again?

**Comment by ISNIT0** [comment]
Summary of my above comments:
- [/] Increase arrow size
- [/] Fix larger resolution search box issues

The "jumping" of the searchbar width on scaling is actually very good for usability.
Without the specific points it's near-impossible for the searchbar to be sensibly sized all the time.

All other points have been fixed in the commits since the review

**Comment by kelson42** [comment]
@Joe To me this is a lot better, only a few things I see left:
* Top bar should not disappear if we are not in "mobile" mode (small resolution)
* Top bar does not disappear on the welcome page if you scroll down, only in articles
* On Firefox, on the welcome page, the magnify glass is invisble
* On firefox, the magnify glass is not centered properly, it is on the top-left corner
* On the welcome page, it is possible to have the search bar in the middle?
* On the welcome page, if small width, the searchbar margin left is far bigger than on the right
* I'm still not happy with the width sizing of the searchbar. I scalles properly up to a certain width around 400px and then it is funky. I would like to just stop growing at a certain size (around 400px would be OK) and then just keep the size.

**Comment by ISNIT0** [comment]
> For some reason, the topbar does not always disappear if I scroll down!
> Top bar should not disappear if we are not in "mobile" mode (small resolution)
> Top bar does not disappear on the welcome page if you scroll down, only in articles

I have a feeling you're seeing this because the hiding is only enabled if the window is `< 520px` when the page is *loaded* (resizing won't trigger the scroll events)

> On Firefox, on the welcome page, the magnify glass is invisble

I see it on Firefox on both small and large screens:
image
image

> On firefox, the magnify glass is not centered properly, it is on the top-left corner

- [ ] I do see this (only on article pages).

> On the welcome page, it is possible to have the search bar in the middle?

This changes the whole structure of the HTML, we really should have decided on this at the beginning...

> On the welcome page, if small width, the searchbar margin left is far bigger than on the right

I don't really understand what you mean here, are you seeing the same as me?
image
image

> I'm still not happy with the width sizing of the searchbar. I scalles properly up to a certain width around 400px and then it is funky. I would like to just stop growing at a certain size (around 400px would be OK) and then just keep the size.

I'm not really sure what you mean, the search bar gets to a maximum of  `20em` when the width gets to `> 645px`. And between `420px` and `645px` it is `36%` width

**Comment by kelson42** [comment]
With "Wikiovyage - Europe" the button is not displayed properl... maybe the ellipsis fails here.

**Comment by ISNIT0** [comment]
- [ ] On Kiwix-Serve homepage the search bar mis-behaves

**Comment by kelson42** [comment]
@ISNIT0 From a user perspective, it looks good to me now. Would like to see all CSS rules properly prefixed with "kiwix" like for the other elements to avoid any potential conflicts with the content.

**Pull request merged**
