### PR TITLE
Fix Dockerfile for ARM

### LINKED ISSUE #407: Failed to build Docker image for ARM
Original base image fails pull when using example command for ARM from modification made in #405:

$ docker build . -t kiwix/kiwix-serve:latest --build-arg ARCH="arm32v7a/"
Sending build context to Docker daemon 3.584kB
Step 1/14 : ARG ARCH=
Step 2/14 : FROM ${ARCH}alpine:3
pull access denied for arm32v7a/alpine, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### PR DESCRIPTION
**Pull request by grahamalderson**
Fixes #407

Returned to original base build alpine:latest because this functions for ARM as well.

### CODE REVIEW

**Comment by kelson42** [comment]
@grahamalderson I have open a ticket for the problem. We prefer to have PR properly linked to issues. If possible as well, we prefer to have feature branches rebased on git `master` (and not git `master` merged in feature branch).

**Comment by kelson42** [comment]
@rgaudin Any feedback on this?

**Comment by rgaudin** [comment]
> @rgaudin Any feedback on this?

look at the ticket

**Comment by kelson42** [comment]
@rgaudin Indeed

**Pull request closed without merging**
