### PR TITLE
Improve usability of docker container

### PR DESCRIPTION
**Pull request by vrillusions**
* Docker container installs `kiwix-manage` to add ability to generate library files.
* entrypoint.sh: Used to handle various arguments passed to container.
* README.md: Update to include the enhancements that were added.

### CODE REVIEW

**Comment by kelson42** [comment]
@vrillusions Thank you for your quality PR, that said, I'm not 100% to understand which problem or which use case this PR resolve. Would you be able to help me on this?

**Comment by rgaudin** [comment]
* Doc implies `generate-library` would refresh library after adding/removing ZIM files but the script only runs `kiwix-manage add`. Is that sufficient?
* entrypoint seems to prevent running a custom command. Could you fix that?

**Comment by vrillusions** [comment]
> 
> 
> @vrillusions Thank you for your quality PR, that said, I'm not 100% sure I understand properly which problem or which use case this PR resolve. Would you be able to help me on this?

Sure.  The way the docker container works now you have two ways of launching it:

```
docker run -v /tmp/zim:/data -p 8080:80 kiwix/kiwix-serve wikipedia.zim
```

This will start the server and will serve a single zim file.  Optionally you can specify multiple zim files to serve several.  The other way it can be started:

```
docker run -v /tmp/zim:/data -p 8080:80 kiwix/kiwix-serve --library library.xml
```

This will load the `library.xml` file and serve all zim files listed.  Problem is there's no way to generate the library file from current container as only `kiwix-serve` is copied over so the idea behind this is the ability to generate the library file from the docker container without the need of any outside sources.

---

>     * Doc implies `generate-library` would refresh library after adding/removing ZIM files but the script only runs `kiwix-manage add`. Is that sufficient?

Ahh I didn't think about that.  Would it be bad to just wipe the `library.xml` file and regenerate it?  Obviously I'd update documentation accordingly but I don't think any custom state is stored in the library file, just metadata from the ZIM files.

> 
>     * entrypoint seems to prevent running a custom command. Could you fix that?

I made entrypoint work the same as it currently does for existing cases.  So both of the examples I mentioned above would work the same.  This just adds the the `generate-library` command.  I'm not sure how to implement running any command without breaking existing use cases.  They way this could be done now is once the container is running doing the following (this assumes you started it with `--name kiwix-serve`:

```
docker exec -it kiwix-serve /bin/sh
```

**Comment by vrillusions** [comment]
Updated so it will remove the library file if it exists before creating it

**Comment by vrillusions** [comment]
sorry about all the branch traffic there I deleted it from my fork and forget it removed it here.  At any rate I noticed there's now a `start.sh` and so updated PR to work with that to allow the generate-library option.  All the other previous handling should be handled by the new `start.sh`

**Comment by stardiviner** [comment]
@vrillusions This PR is helpful for me. Thanks for your PR.

**Comment by kelson42** [comment]
Everything which has been allowed by this PR is now possible. Having a library automatically gnerated has no additonal value in comparison to load multiple ZIMs.

**Pull request closed without merging**
